// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: hyperlane/mailbox/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	io "io"
	math "math"
	math_bits "math/bits"

	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var (
	_ = proto.Marshal
	_ = fmt.Errorf
	_ = math.Inf
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryCurrentTreeMetadataRequest is the request type for the Query/Tree
// metadata RPC method.
type QueryCurrentTreeMetadataRequest struct{}

func (m *QueryCurrentTreeMetadataRequest) Reset()         { *m = QueryCurrentTreeMetadataRequest{} }
func (m *QueryCurrentTreeMetadataRequest) String() string { return proto.CompactTextString(m) }
func (*QueryCurrentTreeMetadataRequest) ProtoMessage()    {}
func (*QueryCurrentTreeMetadataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_567dd9a34f8715cd, []int{0}
}

func (m *QueryCurrentTreeMetadataRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}

func (m *QueryCurrentTreeMetadataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryCurrentTreeMetadataRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}

func (m *QueryCurrentTreeMetadataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCurrentTreeMetadataRequest.Merge(m, src)
}

func (m *QueryCurrentTreeMetadataRequest) XXX_Size() int {
	return m.Size()
}

func (m *QueryCurrentTreeMetadataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCurrentTreeMetadataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCurrentTreeMetadataRequest proto.InternalMessageInfo

// QueryCurrentTreeResponseResponse is the response type for the Query/Tree
// metadata RPC method.
type QueryCurrentTreeMetadataResponse struct {
	Root  []byte `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty"`
	Count uint32 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (m *QueryCurrentTreeMetadataResponse) Reset()         { *m = QueryCurrentTreeMetadataResponse{} }
func (m *QueryCurrentTreeMetadataResponse) String() string { return proto.CompactTextString(m) }
func (*QueryCurrentTreeMetadataResponse) ProtoMessage()    {}
func (*QueryCurrentTreeMetadataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_567dd9a34f8715cd, []int{1}
}

func (m *QueryCurrentTreeMetadataResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}

func (m *QueryCurrentTreeMetadataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryCurrentTreeMetadataResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}

func (m *QueryCurrentTreeMetadataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCurrentTreeMetadataResponse.Merge(m, src)
}

func (m *QueryCurrentTreeMetadataResponse) XXX_Size() int {
	return m.Size()
}

func (m *QueryCurrentTreeMetadataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCurrentTreeMetadataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCurrentTreeMetadataResponse proto.InternalMessageInfo

func (m *QueryCurrentTreeMetadataResponse) GetRoot() []byte {
	if m != nil {
		return m.Root
	}
	return nil
}

func (m *QueryCurrentTreeMetadataResponse) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

// QueryCurrentTreeRequest is the request type for the Query/Tree RPC method
type QueryCurrentTreeRequest struct{}

func (m *QueryCurrentTreeRequest) Reset()         { *m = QueryCurrentTreeRequest{} }
func (m *QueryCurrentTreeRequest) String() string { return proto.CompactTextString(m) }
func (*QueryCurrentTreeRequest) ProtoMessage()    {}
func (*QueryCurrentTreeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_567dd9a34f8715cd, []int{2}
}

func (m *QueryCurrentTreeRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}

func (m *QueryCurrentTreeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryCurrentTreeRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}

func (m *QueryCurrentTreeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCurrentTreeRequest.Merge(m, src)
}

func (m *QueryCurrentTreeRequest) XXX_Size() int {
	return m.Size()
}

func (m *QueryCurrentTreeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCurrentTreeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCurrentTreeRequest proto.InternalMessageInfo

// QueryCurrentTreeResponse is the response type for the Query/Tree RPC method
type QueryCurrentTreeResponse struct {
	Branches [][]byte `protobuf:"bytes,1,rep,name=branches,proto3" json:"branches,omitempty"`
	Count    uint32   `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (m *QueryCurrentTreeResponse) Reset()         { *m = QueryCurrentTreeResponse{} }
func (m *QueryCurrentTreeResponse) String() string { return proto.CompactTextString(m) }
func (*QueryCurrentTreeResponse) ProtoMessage()    {}
func (*QueryCurrentTreeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_567dd9a34f8715cd, []int{3}
}

func (m *QueryCurrentTreeResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}

func (m *QueryCurrentTreeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryCurrentTreeResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}

func (m *QueryCurrentTreeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCurrentTreeResponse.Merge(m, src)
}

func (m *QueryCurrentTreeResponse) XXX_Size() int {
	return m.Size()
}

func (m *QueryCurrentTreeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCurrentTreeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCurrentTreeResponse proto.InternalMessageInfo

func (m *QueryCurrentTreeResponse) GetBranches() [][]byte {
	if m != nil {
		return m.Branches
	}
	return nil
}

func (m *QueryCurrentTreeResponse) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

// QueryDomain is the request type for the Query/Domain RPC
// method.
type QueryDomainRequest struct{}

func (m *QueryDomainRequest) Reset()         { *m = QueryDomainRequest{} }
func (m *QueryDomainRequest) String() string { return proto.CompactTextString(m) }
func (*QueryDomainRequest) ProtoMessage()    {}
func (*QueryDomainRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_567dd9a34f8715cd, []int{4}
}

func (m *QueryDomainRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}

func (m *QueryDomainRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryDomainRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}

func (m *QueryDomainRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDomainRequest.Merge(m, src)
}

func (m *QueryDomainRequest) XXX_Size() int {
	return m.Size()
}

func (m *QueryDomainRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDomainRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDomainRequest proto.InternalMessageInfo

// QueryDomainResponse is the response type for the Query/Domain RPC method.
type QueryDomainResponse struct {
	Domain uint32 `protobuf:"varint,1,opt,name=domain,proto3" json:"domain,omitempty"`
}

func (m *QueryDomainResponse) Reset()         { *m = QueryDomainResponse{} }
func (m *QueryDomainResponse) String() string { return proto.CompactTextString(m) }
func (*QueryDomainResponse) ProtoMessage()    {}
func (*QueryDomainResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_567dd9a34f8715cd, []int{5}
}

func (m *QueryDomainResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}

func (m *QueryDomainResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryDomainResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}

func (m *QueryDomainResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDomainResponse.Merge(m, src)
}

func (m *QueryDomainResponse) XXX_Size() int {
	return m.Size()
}

func (m *QueryDomainResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDomainResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDomainResponse proto.InternalMessageInfo

func (m *QueryDomainResponse) GetDomain() uint32 {
	if m != nil {
		return m.Domain
	}
	return 0
}

func init() {
	proto.RegisterType((*QueryCurrentTreeMetadataRequest)(nil), "hyperlane.mailbox.v1.QueryCurrentTreeMetadataRequest")
	proto.RegisterType((*QueryCurrentTreeMetadataResponse)(nil), "hyperlane.mailbox.v1.QueryCurrentTreeMetadataResponse")
	proto.RegisterType((*QueryCurrentTreeRequest)(nil), "hyperlane.mailbox.v1.QueryCurrentTreeRequest")
	proto.RegisterType((*QueryCurrentTreeResponse)(nil), "hyperlane.mailbox.v1.QueryCurrentTreeResponse")
	proto.RegisterType((*QueryDomainRequest)(nil), "hyperlane.mailbox.v1.QueryDomainRequest")
	proto.RegisterType((*QueryDomainResponse)(nil), "hyperlane.mailbox.v1.QueryDomainResponse")
}

func init() { proto.RegisterFile("hyperlane/mailbox/v1/query.proto", fileDescriptor_567dd9a34f8715cd) }

var fileDescriptor_567dd9a34f8715cd = []byte{
	// 425 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0xc1, 0x6e, 0xd3, 0x40,
	0x14, 0x45, 0x33, 0x2d, 0x8d, 0xd0, 0xd0, 0x6e, 0xa6, 0x11, 0x04, 0x2b, 0x32, 0xc6, 0x80, 0x64,
	0x84, 0xec, 0x51, 0x41, 0xb0, 0x46, 0xc0, 0x12, 0x16, 0x58, 0xac, 0xba, 0x41, 0x63, 0xf7, 0xc9,
	0xb1, 0x64, 0xcf, 0x73, 0x67, 0xc6, 0x56, 0xb3, 0x85, 0x1f, 0xa8, 0xc4, 0x97, 0xf0, 0x17, 0x2c,
	0x2b, 0xc1, 0x82, 0x25, 0x4a, 0xf8, 0x10, 0xc4, 0xd8, 0x49, 0x09, 0x38, 0x10, 0x76, 0x7e, 0xe3,
	0x3b, 0xf7, 0x9e, 0x77, 0x65, 0x53, 0x6f, 0x3a, 0xab, 0x40, 0x15, 0x42, 0x02, 0x2f, 0x45, 0x5e,
	0x24, 0x78, 0xc6, 0x9b, 0x23, 0x7e, 0x5a, 0x83, 0x9a, 0x45, 0x95, 0x42, 0x83, 0x6c, 0xb4, 0x52,
	0x44, 0x9d, 0x22, 0x6a, 0x8e, 0x9c, 0x49, 0x86, 0x98, 0x15, 0xc0, 0x45, 0x95, 0x73, 0x21, 0x25,
	0x1a, 0x61, 0x72, 0x94, 0xba, 0xbd, 0xe3, 0xdf, 0xa6, 0xb7, 0x5e, 0xff, 0xb4, 0x78, 0x5e, 0x2b,
	0x05, 0xd2, 0xbc, 0x51, 0x00, 0xaf, 0xc0, 0x88, 0x13, 0x61, 0x44, 0x0c, 0xa7, 0x35, 0x68, 0xe3,
	0xbf, 0xa4, 0xde, 0x66, 0x89, 0xae, 0x50, 0x6a, 0x60, 0x8c, 0x5e, 0x51, 0x88, 0x66, 0x4c, 0x3c,
	0x12, 0xec, 0xc7, 0xf6, 0x99, 0x8d, 0xe8, 0x5e, 0x8a, 0xb5, 0x34, 0xe3, 0x1d, 0x8f, 0x04, 0x07,
	0x71, 0x3b, 0xf8, 0x37, 0xe9, 0x8d, 0xdf, 0xdd, 0x2e, 0x83, 0xc6, 0x7f, 0xbe, 0xea, 0x02, 0x1c,
	0x7a, 0x35, 0x51, 0x42, 0xa6, 0x53, 0xd0, 0x63, 0xe2, 0xed, 0x06, 0xfb, 0xf1, 0x6a, 0xde, 0x10,
	0x34, 0xa2, 0xcc, 0xba, 0xbd, 0xc0, 0x52, 0xe4, 0x72, 0x99, 0x11, 0xd2, 0xc3, 0xb5, 0xd3, 0xce,
	0xfe, 0x3a, 0x1d, 0x9e, 0xd8, 0x13, 0xbb, 0xc1, 0x41, 0xdc, 0x4d, 0x0f, 0xbf, 0xec, 0xd2, 0x3d,
	0xab, 0x67, 0x1f, 0x09, 0x3d, 0xec, 0x69, 0x80, 0x3d, 0x8e, 0xfa, 0x5a, 0x8f, 0xfe, 0x51, 0xaa,
	0xf3, 0xe4, 0x7f, 0xaf, 0xb5, 0xa0, 0xfe, 0x83, 0x77, 0x9f, 0xbf, 0x7f, 0xd8, 0xb9, 0xc7, 0xee,
	0xf0, 0xde, 0xcf, 0xc1, 0x28, 0x80, 0xb7, 0xe5, 0x92, 0xed, 0x3d, 0xa1, 0xc3, 0x76, 0x51, 0x16,
	0xfc, 0x25, 0x6f, 0xad, 0x21, 0xe7, 0xfe, 0x16, 0xca, 0x0e, 0xe6, 0xae, 0x85, 0x71, 0xd9, 0xa4,
	0x1f, 0xa6, 0xed, 0x90, 0x9d, 0x13, 0x7a, 0xed, 0x97, 0x95, 0x58, 0xb8, 0xdd, 0xea, 0x4b, 0x9e,
	0x68, 0x5b, 0x79, 0x07, 0xe5, 0x5b, 0xa8, 0x09, 0x73, 0x36, 0x37, 0xf4, 0xec, 0xf8, 0xd3, 0xdc,
	0x25, 0x17, 0x73, 0x97, 0x7c, 0x9b, 0xbb, 0xe4, 0x7c, 0xe1, 0x0e, 0x2e, 0x16, 0xee, 0xe0, 0xeb,
	0xc2, 0x1d, 0x1c, 0x3f, 0xcd, 0x72, 0x33, 0xad, 0x93, 0x28, 0xc5, 0x92, 0x6b, 0xa3, 0x84, 0xcc,
	0xa0, 0xc0, 0x06, 0xc2, 0x06, 0xa4, 0xa9, 0x15, 0xe8, 0x4b, 0xd3, 0x30, 0x45, 0x5d, 0xa2, 0xe6,
	0x67, 0x2b, 0x77, 0x33, 0xab, 0x40, 0x27, 0x43, 0xfb, 0x63, 0x3d, 0xfa, 0x11, 0x00, 0x00, 0xff,
	0xff, 0x15, 0x17, 0x10, 0x83, 0xb0, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var (
	_ context.Context
	_ grpc.ClientConn
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Get current tree metadata
	CurrentTreeMetadata(ctx context.Context, in *QueryCurrentTreeMetadataRequest, opts ...grpc.CallOption) (*QueryCurrentTreeMetadataResponse, error)
	// Get domain
	Domain(ctx context.Context, in *QueryDomainRequest, opts ...grpc.CallOption) (*QueryDomainResponse, error)
	// Get current tree
	CurrentTree(ctx context.Context, in *QueryCurrentTreeRequest, opts ...grpc.CallOption) (*QueryCurrentTreeResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) CurrentTreeMetadata(ctx context.Context, in *QueryCurrentTreeMetadataRequest, opts ...grpc.CallOption) (*QueryCurrentTreeMetadataResponse, error) {
	out := new(QueryCurrentTreeMetadataResponse)
	err := c.cc.Invoke(ctx, "/hyperlane.mailbox.v1.Query/CurrentTreeMetadata", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Domain(ctx context.Context, in *QueryDomainRequest, opts ...grpc.CallOption) (*QueryDomainResponse, error) {
	out := new(QueryDomainResponse)
	err := c.cc.Invoke(ctx, "/hyperlane.mailbox.v1.Query/Domain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) CurrentTree(ctx context.Context, in *QueryCurrentTreeRequest, opts ...grpc.CallOption) (*QueryCurrentTreeResponse, error) {
	out := new(QueryCurrentTreeResponse)
	err := c.cc.Invoke(ctx, "/hyperlane.mailbox.v1.Query/CurrentTree", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Get current tree metadata
	CurrentTreeMetadata(context.Context, *QueryCurrentTreeMetadataRequest) (*QueryCurrentTreeMetadataResponse, error)
	// Get domain
	Domain(context.Context, *QueryDomainRequest) (*QueryDomainResponse, error)
	// Get current tree
	CurrentTree(context.Context, *QueryCurrentTreeRequest) (*QueryCurrentTreeResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct{}

func (*UnimplementedQueryServer) CurrentTreeMetadata(ctx context.Context, req *QueryCurrentTreeMetadataRequest) (*QueryCurrentTreeMetadataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CurrentTreeMetadata not implemented")
}

func (*UnimplementedQueryServer) Domain(ctx context.Context, req *QueryDomainRequest) (*QueryDomainResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Domain not implemented")
}

func (*UnimplementedQueryServer) CurrentTree(ctx context.Context, req *QueryCurrentTreeRequest) (*QueryCurrentTreeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CurrentTree not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_CurrentTreeMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryCurrentTreeMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).CurrentTreeMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hyperlane.mailbox.v1.Query/CurrentTreeMetadata",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).CurrentTreeMetadata(ctx, req.(*QueryCurrentTreeMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Domain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDomainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Domain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hyperlane.mailbox.v1.Query/Domain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Domain(ctx, req.(*QueryDomainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_CurrentTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryCurrentTreeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).CurrentTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hyperlane.mailbox.v1.Query/CurrentTree",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).CurrentTree(ctx, req.(*QueryCurrentTreeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hyperlane.mailbox.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CurrentTreeMetadata",
			Handler:    _Query_CurrentTreeMetadata_Handler,
		},
		{
			MethodName: "Domain",
			Handler:    _Query_Domain_Handler,
		},
		{
			MethodName: "CurrentTree",
			Handler:    _Query_CurrentTree_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hyperlane/mailbox/v1/query.proto",
}

func (m *QueryCurrentTreeMetadataRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryCurrentTreeMetadataRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryCurrentTreeMetadataRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryCurrentTreeMetadataResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryCurrentTreeMetadataResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryCurrentTreeMetadataResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Count != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Count))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Root) > 0 {
		i -= len(m.Root)
		copy(dAtA[i:], m.Root)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Root)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryCurrentTreeRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryCurrentTreeRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryCurrentTreeRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryCurrentTreeResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryCurrentTreeResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryCurrentTreeResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Count != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Count))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Branches) > 0 {
		for iNdEx := len(m.Branches) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Branches[iNdEx])
			copy(dAtA[i:], m.Branches[iNdEx])
			i = encodeVarintQuery(dAtA, i, uint64(len(m.Branches[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryDomainRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryDomainRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryDomainRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryDomainResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryDomainResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryDomainResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Domain != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Domain))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}

func (m *QueryCurrentTreeMetadataRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryCurrentTreeMetadataResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Root)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Count != 0 {
		n += 1 + sovQuery(uint64(m.Count))
	}
	return n
}

func (m *QueryCurrentTreeRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryCurrentTreeResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Branches) > 0 {
		for _, b := range m.Branches {
			l = len(b)
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Count != 0 {
		n += 1 + sovQuery(uint64(m.Count))
	}
	return n
}

func (m *QueryDomainRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryDomainResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Domain != 0 {
		n += 1 + sovQuery(uint64(m.Domain))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}

func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}

func (m *QueryCurrentTreeMetadataRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryCurrentTreeMetadataRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryCurrentTreeMetadataRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *QueryCurrentTreeMetadataResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryCurrentTreeMetadataResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryCurrentTreeMetadataResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Root", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Root = append(m.Root[:0], dAtA[iNdEx:postIndex]...)
			if m.Root == nil {
				m.Root = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Count", wireType)
			}
			m.Count = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Count |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *QueryCurrentTreeRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryCurrentTreeRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryCurrentTreeRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *QueryCurrentTreeResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryCurrentTreeResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryCurrentTreeResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Branches", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Branches = append(m.Branches, make([]byte, postIndex-iNdEx))
			copy(m.Branches[len(m.Branches)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Count", wireType)
			}
			m.Count = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Count |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *QueryDomainRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryDomainRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryDomainRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *QueryDomainResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryDomainResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryDomainResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Domain", wireType)
			}
			m.Domain = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Domain |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
