// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: hyperlane/mailbox/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	io "io"
	math "math"
	math_bits "math/bits"

	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var (
	_ = proto.Marshal
	_ = fmt.Errorf
	_ = math.Inf
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryCurrentTreeMetadataRequest is the request type for the Query/Tree RPC
// method.
type QueryCurrentTreeMetadataRequest struct{}

func (m *QueryCurrentTreeMetadataRequest) Reset()         { *m = QueryCurrentTreeMetadataRequest{} }
func (m *QueryCurrentTreeMetadataRequest) String() string { return proto.CompactTextString(m) }
func (*QueryCurrentTreeMetadataRequest) ProtoMessage()    {}
func (*QueryCurrentTreeMetadataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_567dd9a34f8715cd, []int{0}
}

func (m *QueryCurrentTreeMetadataRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}

func (m *QueryCurrentTreeMetadataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryCurrentTreeMetadataRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}

func (m *QueryCurrentTreeMetadataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCurrentTreeMetadataRequest.Merge(m, src)
}

func (m *QueryCurrentTreeMetadataRequest) XXX_Size() int {
	return m.Size()
}

func (m *QueryCurrentTreeMetadataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCurrentTreeMetadataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCurrentTreeMetadataRequest proto.InternalMessageInfo

// QueryTreeResponse is the response type for the Query/Tree RPC method.
type QueryCurrentTreeMetadataResponse struct {
	Root  []byte `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty"`
	Count uint32 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (m *QueryCurrentTreeMetadataResponse) Reset()         { *m = QueryCurrentTreeMetadataResponse{} }
func (m *QueryCurrentTreeMetadataResponse) String() string { return proto.CompactTextString(m) }
func (*QueryCurrentTreeMetadataResponse) ProtoMessage()    {}
func (*QueryCurrentTreeMetadataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_567dd9a34f8715cd, []int{1}
}

func (m *QueryCurrentTreeMetadataResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}

func (m *QueryCurrentTreeMetadataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryCurrentTreeMetadataResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}

func (m *QueryCurrentTreeMetadataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCurrentTreeMetadataResponse.Merge(m, src)
}

func (m *QueryCurrentTreeMetadataResponse) XXX_Size() int {
	return m.Size()
}

func (m *QueryCurrentTreeMetadataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCurrentTreeMetadataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCurrentTreeMetadataResponse proto.InternalMessageInfo

func (m *QueryCurrentTreeMetadataResponse) GetRoot() []byte {
	if m != nil {
		return m.Root
	}
	return nil
}

func (m *QueryCurrentTreeMetadataResponse) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func init() {
	proto.RegisterType((*QueryCurrentTreeMetadataRequest)(nil), "hyperlane.mailbox.v1.QueryCurrentTreeMetadataRequest")
	proto.RegisterType((*QueryCurrentTreeMetadataResponse)(nil), "hyperlane.mailbox.v1.QueryCurrentTreeMetadataResponse")
}

func init() { proto.RegisterFile("hyperlane/mailbox/v1/query.proto", fileDescriptor_567dd9a34f8715cd) }

var fileDescriptor_567dd9a34f8715cd = []byte{
	// 299 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0xb1, 0x4a, 0x03, 0x41,
	0x10, 0x86, 0xb3, 0xc1, 0x58, 0x2c, 0xda, 0xac, 0x29, 0x42, 0x08, 0xeb, 0x79, 0x55, 0x9a, 0xec,
	0x12, 0x45, 0x6b, 0xd1, 0x56, 0x0b, 0x83, 0x55, 0xba, 0x4d, 0x1c, 0x2e, 0x07, 0x97, 0x9d, 0xcb,
	0xee, 0xec, 0x91, 0xb4, 0x3e, 0x81, 0xe0, 0x4b, 0x58, 0xfb, 0x14, 0x96, 0x01, 0x1b, 0x4b, 0x49,
	0x7c, 0x10, 0x31, 0x27, 0xb1, 0x39, 0x11, 0xbb, 0x5d, 0xf8, 0xfe, 0x8f, 0x7f, 0x66, 0x78, 0x34,
	0x59, 0xe4, 0xe0, 0x32, 0x63, 0x41, 0x4f, 0x4d, 0x9a, 0x8d, 0x70, 0xae, 0x8b, 0xbe, 0x9e, 0x05,
	0x70, 0x0b, 0x95, 0x3b, 0x24, 0x14, 0xcd, 0x2d, 0xa1, 0xbe, 0x09, 0x55, 0xf4, 0xdb, 0x9d, 0x04,
	0x31, 0xc9, 0x40, 0x9b, 0x3c, 0xd5, 0xc6, 0x5a, 0x24, 0x43, 0x29, 0x5a, 0x5f, 0x66, 0xe2, 0x23,
	0x7e, 0x78, 0xf3, 0xa5, 0xb8, 0x0c, 0xce, 0x81, 0xa5, 0x5b, 0x07, 0x70, 0x0d, 0x64, 0xee, 0x0c,
	0x99, 0x01, 0xcc, 0x02, 0x78, 0x8a, 0xaf, 0x78, 0xf4, 0x3b, 0xe2, 0x73, 0xb4, 0x1e, 0x84, 0xe0,
	0x3b, 0x0e, 0x91, 0x5a, 0x2c, 0x62, 0xdd, 0xbd, 0xc1, 0xe6, 0x2d, 0x9a, 0xbc, 0x31, 0xc6, 0x60,
	0xa9, 0x55, 0x8f, 0x58, 0x77, 0x7f, 0x50, 0x7e, 0x8e, 0x9f, 0x19, 0x6f, 0x6c, 0x74, 0xe2, 0x89,
	0xf1, 0x83, 0x0a, 0xa7, 0x38, 0x55, 0x55, 0x73, 0xa8, 0x3f, 0x6a, 0xb6, 0xcf, 0xfe, 0x1b, 0x2b,
	0xab, 0xc7, 0xf1, 0xfd, 0xeb, 0xc7, 0x63, 0xbd, 0x23, 0xda, 0xba, 0x72, 0xc1, 0xe4, 0x00, 0x2e,
	0x86, 0x2f, 0x2b, 0xc9, 0x96, 0x2b, 0xc9, 0xde, 0x57, 0x92, 0x3d, 0xac, 0x65, 0x6d, 0xb9, 0x96,
	0xb5, 0xb7, 0xb5, 0xac, 0x0d, 0xcf, 0x93, 0x94, 0x26, 0x61, 0xa4, 0xc6, 0x38, 0xd5, 0x9e, 0x9c,
	0xb1, 0x09, 0x64, 0x58, 0x40, 0xaf, 0x00, 0x4b, 0xc1, 0x81, 0xff, 0x91, 0xf6, 0xc6, 0xe8, 0xa7,
	0xe8, 0xf5, 0x7c, 0x6b, 0xa7, 0x45, 0x0e, 0x7e, 0xb4, 0xbb, 0x39, 0xc4, 0xc9, 0x67, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xed, 0x8d, 0x11, 0x66, 0xe0, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var (
	_ context.Context
	_ grpc.ClientConn
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Get current tree metadata
	CurrentTreeMetadata(ctx context.Context, in *QueryCurrentTreeMetadataRequest, opts ...grpc.CallOption) (*QueryCurrentTreeMetadataResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) CurrentTreeMetadata(ctx context.Context, in *QueryCurrentTreeMetadataRequest, opts ...grpc.CallOption) (*QueryCurrentTreeMetadataResponse, error) {
	out := new(QueryCurrentTreeMetadataResponse)
	err := c.cc.Invoke(ctx, "/hyperlane.mailbox.v1.Query/CurrentTreeMetadata", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Get current tree metadata
	CurrentTreeMetadata(context.Context, *QueryCurrentTreeMetadataRequest) (*QueryCurrentTreeMetadataResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct{}

func (*UnimplementedQueryServer) CurrentTreeMetadata(ctx context.Context, req *QueryCurrentTreeMetadataRequest) (*QueryCurrentTreeMetadataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CurrentTreeMetadata not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_CurrentTreeMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryCurrentTreeMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).CurrentTreeMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hyperlane.mailbox.v1.Query/CurrentTreeMetadata",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).CurrentTreeMetadata(ctx, req.(*QueryCurrentTreeMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hyperlane.mailbox.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CurrentTreeMetadata",
			Handler:    _Query_CurrentTreeMetadata_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hyperlane/mailbox/v1/query.proto",
}

func (m *QueryCurrentTreeMetadataRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryCurrentTreeMetadataRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryCurrentTreeMetadataRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryCurrentTreeMetadataResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryCurrentTreeMetadataResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryCurrentTreeMetadataResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Count != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Count))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Root) > 0 {
		i -= len(m.Root)
		copy(dAtA[i:], m.Root)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Root)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}

func (m *QueryCurrentTreeMetadataRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryCurrentTreeMetadataResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Root)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Count != 0 {
		n += 1 + sovQuery(uint64(m.Count))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}

func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}

func (m *QueryCurrentTreeMetadataRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryCurrentTreeMetadataRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryCurrentTreeMetadataRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *QueryCurrentTreeMetadataResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryCurrentTreeMetadataResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryCurrentTreeMetadataResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Root", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Root = append(m.Root[:0], dAtA[iNdEx:postIndex]...)
			if m.Root == nil {
				m.Root = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Count", wireType)
			}
			m.Count = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Count |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
